persistence true
persistence_location /mosquitto/data/
per_listener_settings true

listener 1883
allow_anonymous false
password_file /mosquitto/config/passwordfile

listener 1884
allow_anonymous true

log_dest file /mosquitto/log/mosquitto.log
